# Generated by Django 6.1.1 on 2026-09-23 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_status', models.CharField(blank=True, choices=[('8th', '8th Standard'), ('9th', '9th Standard'), ('10th', '10th Standard'), ('11th', '11th Standard'), ('12th', '12th Standard'), ('pursuing-ug', 'Pursuing UG'), ('completed-ug', 'Completed UG')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
