const ipipJunior50 = [
  {
    id: "J01",
    statement: "I am the life of the party.",
    factor: "Extraversion",
    reverse: false,
  },
  {
    id: "J02",
    statement: "I feel little concern for others.",
    factor: "Agreeableness",
    reverse: true,
  },
  {
    id: "J03",
    statement: "I am always prepared.",
    factor: "Conscientiousness",
    reverse: false,
  },
  {
    id: "J04",
    statement: "I get stressed out easily.",
    factor: "Emotional Stability",
    reverse: true,
  },
  {
    id: "J05",
    statement: "I have a rich vocabulary.",
    factor: "Intellect",
    reverse: false,
  },
  {
    id: "J06",
    statement: "I don't talk a lot.",
    factor: "Extraversion",
    reverse: true,
  },
  {
    id: "J07",
    statement: "I am interested in people.",
    factor: "Agreeableness",
    reverse: false,
  },
  {
    id: "J08",
    statement: "I leave my belongings around.",
    factor: "Conscientiousness",
    reverse: true,
  },
  {
    id: "J09",
    statement: "I am relaxed most of the time.",
    factor: "Emotional Stability",
    reverse: false,
  },
  {
    id: "J10",
    statement: "I have difficulty understanding abstract ideas.",
    factor: "Intellect",
    reverse: true,
  },
  {
    id: "J11",
    statement: "I feel comfortable around people.",
    factor: "Extraversion",
    reverse: false,
  },
  {
    id: "J12",
    statement: "I insult people.",
    factor: "Agreeableness",
    reverse: true,
  },
  {
    id: "J13",
    statement: "I pay attention to details.",
    factor: "Conscientiousness",
    reverse: false,
  },
  {
    id: "J14",
    statement: "I worry about things.",
    factor: "Emotional Stability",
    reverse: true,
  },
  {
    id: "J15",
    statement: "I have a vivid imagination.",
    factor: "Intellect",
    reverse: false,
  },
  {
    id: "J16",
    statement: "I keep in the background.",
    factor: "Extraversion",
    reverse: true,
  },
  {
    id: "J17",
    statement: "I sympathize with others' feelings.",
    factor: "Agreeableness",
    reverse: false,
  },
  {
    id: "J18",
    statement: "I make a mess of things.",
    factor: "Conscientiousness",
    reverse: true,
  },
  {
    id: "J19",
    statement: "I seldom feel blue.",
    factor: "Emotional Stability",
    reverse: false,
  },
  {
    id: "J20",
    statement: "I am not interested in abstract ideas.",
    factor: "Intellect",
    reverse: true,
  },
  {
    id: "J21",
    statement: "I start conversations.",
    factor: "Extraversion",
    reverse: false,
  },
  {
    id: "J22",
    statement: "I am not interested in other people's problems.",
    factor: "Agreeableness",
    reverse: true,
  },
  {
    id: "J23",
    statement: "I get chores done right away.",
    factor: "Conscientiousness",
    reverse: false,
  },
  {
    id: "J24",
    statement: "I am easily disturbed.",
    factor: "Emotional Stability",
    reverse: true,
  },
  {
    id: "J25",
    statement: "I have excellent ideas.",
    factor: "Intellect",
    reverse: false,
  },
  {
    id: "J26",
    statement: "I have little to say.",
    factor: "Extraversion",
    reverse: true,
  },
  {
    id: "J27",
    statement: "I have a soft heart.",
    factor: "Agreeableness",
    reverse: false,
  },
  {
    id: "J28",
    statement: "I often forget to put things back in their proper place.",
    factor: "Conscientiousness",
    reverse: true,
  },
  {
    id: "J29",
    statement: "I get upset easily.",
    factor: "Emotional Stability",
    reverse: true,
  },
  {
    id: "J30",
    statement: "I do not have a good imagination.",
    factor: "Intellect",
    reverse: true,
  },
  {
    id: "J31",
    statement: "I talk to a lot of different people at parties.",
    factor: "Extraversion",
    reverse: false,
  },
  {
    id: "J32",
    statement: "I am not really interested in others.",
    factor: "Agreeableness",
    reverse: true,
  },
  {
    id: "J33",
    statement: "I like order.",
    factor: "Conscientiousness",
    reverse: false,
  },
  {
    id: "J34",
    statement: "I change my mood a lot.",
    factor: "Emotional Stability",
    reverse: true,
  },
  {
    id: "J35",
    statement: "I am quick to understand things.",
    factor: "Intellect",
    reverse: false,
  },
  {
    id: "J36",
    statement: "I don't like to draw attention to myself.",
    factor: "Extraversion",
    reverse: true,
  },
  {
    id: "J37",
    statement: "I take time out for others.",
    factor: "Agreeableness",
    reverse: false,
  },
  {
    id: "J38",
    statement: "I shirk my duties.",
    factor: "Conscientiousness",
    reverse: true,
  },
  {
    id: "J39",
    statement: "I have frequent mood swings.",
    factor: "Emotional Stability",
    reverse: true,
  },
  {
    id: "J40",
    statement: "I use difficult words.",
    factor: "Intellect",
    reverse: false,
  },
  {
    id: "J41",
    statement: "I don't mind being the center of attention.",
    factor: "Extraversion",
    reverse: false,
  },
  {
    id: "J42",
    statement: "I feel others' emotions.",
    factor: "Agreeableness",
    reverse: false,
  },
  {
    id: "J43",
    statement: "I follow a schedule.",
    factor: "Conscientiousness",
    reverse: false,
  },
  {
    id: "J44",
    statement: "I get irritated easily.",
    factor: "Emotional Stability",
    reverse: true,
  },
  {
    id: "J45",
    statement: "I spend time reflecting on things.",
    factor: "Intellect",
    reverse: false,
  },
  {
    id: "J46",
    statement: "I am quiet around strangers.",
    factor: "Extraversion",
    reverse: true,
  },
  {
    id: "J47",
    statement: "I make people feel at ease.",
    factor: "Agreeableness",
    reverse: false,
  },
  {
    id: "J48",
    statement: "I am exacting in my work.",
    factor: "Conscientiousness",
    reverse: false,
  },
  {
    id: "J49",
    statement: "I often feel blue.",
    factor: "Emotional Stability",
    reverse: true,
  },
  {
    id: "J50",
    statement: "I am full of ideas.",
    factor: "Intellect",
    reverse: false,
  },
];

export default ipipJunior50;