# Generated by Django 6.1.1 on 2026-09-23 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentattempt_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoring_version', models.CharField(default='1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.assessmentattempt')),
            ],
        ),
        migrations.CreateModel(
            name='DimensionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.FloatField()),
                ('normalized_score', models.FloatField()),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.dimension')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_results', to='assessments.assessmentresult')),
            ],
            options={
                'ordering': ['dimension__name'],
                'unique_together': {('result', 'dimension')},
            },
        ),
    ]
