# Generated by Django 6.1.1 on 2026-09-24 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentresult_dimensionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoring_method', models.CharField(choices=[('dimension_based', 'Dimension Based')], default='dimension_based', max_length=50)),
                ('aggregation_method', models.CharField(choices=[('sum', 'Sum'), ('mean', 'Mean'), ('weighted_mean', 'Weighted Mean')], default='mean', max_length=50)),
                ('reverse_rule', models.CharField(choices=[('min_plus_max_minus', 'Minimum + Maximum - Response')], default='min_plus_max_minus', max_length=50)),
                ('normalization_method', models.CharField(choices=[('none', 'No Normalization'), ('linear', 'Linear Normalization')], default='linear', max_length=50)),
                ('input_min', models.FloatField(default=1.0)),
                ('input_max', models.FloatField(default=5.0)),
                ('output_min', models.FloatField(default=0.0)),
                ('output_max', models.FloatField(default=100.0)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_configuration', to='assessments.assessment')),
            ],
        ),
    ]
