# Generated by Django 6.1.1 on 2026-09-24 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_scoringconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_status', models.CharField(choices=[('8th', '8th Standard'), ('9th', '9th Standard'), ('10th', '10th Standard'), ('11th', '11th Standard'), ('12th', '12th Standard'), ('pursuing-ug', 'Pursuing UG'), ('completed-ug', 'Completed UG')], max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assessments.assessment')),
            ],
            options={
                'ordering': ['student_status'],
            },
        ),
    ]
